### ISSUE TITLE
reauth giving error "Something unexpected happened.  Please try again."

### ISSUE THREAD

**Issue by drasch** [davars/sohop#2]
Trying to reauth to a service this morning I got errors about "Something unexpected happened.  Please try again."  I tried again many times, then at some point something unexpected stopped happening and it started working.

**Comment by davars** [comment]
This happens when the oauth/authorize endpoint is called with a state parameter that does not match the (possibly) nil state parameter in the session.  Go to https://oauth.<domain>/session to view.

I've gotten reports that this happens when loading multiple tabs to the same proxy instance while logged out, triggering multiple simultaneous authentications (since they'll stomp on each other's cookie data).  I'll try to think of a way to handle multiple simultaneous logins...
